[phases.setup]
nixPkgs = ["php82", "php82Extensions.composer", "apacheHttpd", "php82Extensions.pdo_pgsql"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan route:cache", 
  "php artisan view:cache",
  "php artisan storage:link"
]

[start]
cmd = "vendor/bin/heroku-php-apache2 public/"
