[build]
builder = "nixpacks"

[build.environment]
PHP_VERSION = "8.3"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.environment]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stack"
LOG_LEVEL = "error"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
QUEUE_CONNECTION = "sync"
