import React, { useMemo } from 'react'
import { OptimizedIcon } from '@/components/ui/optimized-icon'

const iconCache = new Map<string, React.ReactElement>()

export const useOptimizedIcons = () => {
  const getIcon = (name: string, props?: any) => {
    const cacheKey = `${name}-${JSON.stringify(props || {})}`

    if (iconCache.has(cacheKey)) {
      return iconCache.get(cacheKey)
    }

    const icon = React.createElement(OptimizedIcon, { name, ...props })
    iconCache.set(cacheKey, icon)

    return icon
  }

  const commonIcons = useMemo(() => ({
    // Icônes principales utilisées dans les paramètres
    user: (props?: any) => getIcon('user', props),
    mail: (props?: any) => getIcon('mail', props),
    phone: (props?: any) => getIcon('phone', props),
    settings: (props?: any) => getIcon('settings', props),
    bell: (props?: any) => getIcon('bell', props),
    shield: (props?: any) => getIcon('shield', props),
    building: (props?: any) => getIcon('building', props),
    globe: (props?: any) => getIcon('globe', props),
    'map-pin': (props?: any) => getIcon('map-pin', props),
    lock: (props?: any) => getIcon('lock', props),
    'credit-card': (props?: any) => getIcon('credit-card', props),
    file: (props?: any) => getIcon('file', props),
    search: (props?: any) => getIcon('search', props),
    database: (props?: any) => getIcon('database', props),
    api: (props?: any) => getIcon('api', props),
    'alert-triangle': (props?: any) => getIcon('alert-triangle', props),
    
    // Icônes utilitaires
    check: (props?: any) => getIcon('check', props),
    x: (props?: any) => getIcon('x', props),
    plus: (props?: any) => getIcon('plus', props),
    minus: (props?: any) => getIcon('minus', props),
    edit: (props?: any) => getIcon('edit', props),
    trash: (props?: any) => getIcon('trash', props),
    eye: (props?: any) => getIcon('eye', props),
    'eye-off': (props?: any) => getIcon('eye-off', props),
    filter: (props?: any) => getIcon('filter', props),
    'chevron-down': (props?: any) => getIcon('chevron-down', props),
    'chevron-up': (props?: any) => getIcon('chevron-up', props),
    'chevron-left': (props?: any) => getIcon('chevron-left', props),
    'chevron-right': (props?: any) => getIcon('chevron-right', props),
    menu: (props?: any) => getIcon('menu', props),
    close: (props?: any) => getIcon('x', props),
    home: (props?: any) => getIcon('home', props),
    dashboard: (props?: any) => getIcon('dashboard', props),
    'shopping-cart': (props?: any) => getIcon('shopping-cart', props),
    package: (props?: any) => getIcon('package', props),
    users: (props?: any) => getIcon('users', props),
    'chart-bar': (props?: any) => getIcon('chart-bar', props),
    'trending-up': (props?: any) => getIcon('trending-up', props),
    'trending-down': (props?: any) => getIcon('trending-down', props),
    refresh: (props?: any) => getIcon('refresh', props),
    download: (props?: any) => getIcon('download', props),
    upload: (props?: any) => getIcon('upload', props),
    copy: (props?: any) => getIcon('copy', props),
    share: (props?: any) => getIcon('share', props),
    heart: (props?: any) => getIcon('heart', props),
    star: (props?: any) => getIcon('star', props),
    flag: (props?: any) => getIcon('flag', props),
    'alert-circle': (props?: any) => getIcon('alert-circle', props),
    info: (props?: any) => getIcon('info', props),
    'check-circle': (props?: any) => getIcon('check-circle', props),
    'x-circle': (props?: any) => getIcon('x-circle', props),
    loader: (props?: any) => getIcon('loader', props),
    calendar: (props?: any) => getIcon('calendar', props),
    clock: (props?: any) => getIcon('clock', props),
    tag: (props?: any) => getIcon('tag', props),
    image: (props?: any) => getIcon('image', props),
    folder: (props?: any) => getIcon('folder', props),
    server: (props?: any) => getIcon('server', props),
    cloud: (props?: any) => getIcon('cloud', props),
    wifi: (props?: any) => getIcon('wifi', props),
    'wifi-off': (props?: any) => getIcon('wifi-off', props),
    battery: (props?: any) => getIcon('battery', props),
    'battery-off': (props?: any) => getIcon('battery-off', props),
    volume: (props?: any) => getIcon('volume', props),
    'volume-off': (props?: any) => getIcon('volume-off', props),
    sun: (props?: any) => getIcon('sun', props),
    moon: (props?: any) => getIcon('moon', props),
    palette: (props?: any) => getIcon('palette', props),
    brush: (props?: any) => getIcon('brush', props),
    code: (props?: any) => getIcon('code', props),
    terminal: (props?: any) => getIcon('terminal', props),
    bug: (props?: any) => getIcon('bug', props),
    rocket: (props?: any) => getIcon('rocket', props),
    zap: (props?: any) => getIcon('zap', props),
    target: (props?: any) => getIcon('target', props),
    award: (props?: any) => getIcon('award', props),
    trophy: (props?: any) => getIcon('trophy', props),
    gift: (props?: any) => getIcon('gift', props),
    'shopping-bag': (props?: any) => getIcon('shopping-bag', props),
    receipt: (props?: any) => getIcon('receipt', props),
    coins: (props?: any) => getIcon('coins', props),
    banknote: (props?: any) => getIcon('banknote', props),
    wallet: (props?: any) => getIcon('wallet', props),
    'piggy-bank': (props?: any) => getIcon('piggy-bank', props),
    'chart-line': (props?: any) => getIcon('chart-line', props),
    'chart-pie': (props?: any) => getIcon('chart-pie', props),
    activity: (props?: any) => getIcon('activity', props),
    pulse: (props?: any) => getIcon('pulse', props),
    heartbeat: (props?: any) => getIcon('heartbeat', props),
    thermometer: (props?: any) => getIcon('thermometer', props),
    gauge: (props?: any) => getIcon('gauge', props),
    compass: (props?: any) => getIcon('compass', props),
    map: (props?: any) => getIcon('map', props),
    navigation: (props?: any) => getIcon('navigation', props),
    route: (props?: any) => getIcon('route', props),
    car: (props?: any) => getIcon('car', props),
    plane: (props?: any) => getIcon('plane', props),
    train: (props?: any) => getIcon('train', props),
    bus: (props?: any) => getIcon('bus', props),
    bike: (props?: any) => getIcon('bike', props),
    gamepad: (props?: any) => getIcon('gamepad', props),
    headphones: (props?: any) => getIcon('headphones', props),
    microphone: (props?: any) => getIcon('microphone', props),
    camera: (props?: any) => getIcon('camera', props),
    video: (props?: any) => getIcon('video', props),
    play: (props?: any) => getIcon('play', props),
    pause: (props?: any) => getIcon('pause', props),
    stop: (props?: any) => getIcon('stop', props),
    'skip-back': (props?: any) => getIcon('skip-back', props),
    'skip-forward': (props?: any) => getIcon('skip-forward', props),
    repeat: (props?: any) => getIcon('repeat', props),
    shuffle: (props?: any) => getIcon('shuffle', props),
    maximize: (props?: any) => getIcon('maximize', props),
    minimize: (props?: any) => getIcon('minimize', props),
    fullscreen: (props?: any) => getIcon('fullscreen', props),
    'fullscreen-exit': (props?: any) => getIcon('fullscreen-exit', props),
    move: (props?: any) => getIcon('move', props),
    rotate: (props?: any) => getIcon('rotate', props),
    crop: (props?: any) => getIcon('crop', props),
    cut: (props?: any) => getIcon('cut', props),
    paste: (props?: any) => getIcon('paste', props),
    clipboard: (props?: any) => getIcon('clipboard', props),
    bookmark: (props?: any) => getIcon('bookmark', props),
    archive: (props?: any) => getIcon('archive', props),
    inbox: (props?: any) => getIcon('inbox', props),
    send: (props?: any) => getIcon('send', props),
    email: (props?: any) => getIcon('email', props),
    message: (props?: any) => getIcon('message', props),
    call: (props?: any) => getIcon('call', props),
    'video-call': (props?: any) => getIcon('video-call', props),
    mic: (props?: any) => getIcon('mic', props),
    headset: (props?: any) => getIcon('headset', props),
    sound: (props?: any) => getIcon('sound', props),
    speaker: (props?: any) => getIcon('speaker', props),
    radio: (props?: any) => getIcon('radio', props),
    tv: (props?: any) => getIcon('tv', props),
    monitor: (props?: any) => getIcon('monitor', props),
    laptop: (props?: any) => getIcon('laptop', props),
    tablet: (props?: any) => getIcon('tablet', props),
    watch: (props?: any) => getIcon('watch', props),
  }), [])

  return { icons: commonIcons, getIcon }
}