name: coovia-backend
services:
- name: backend
  source_dir: /backend
  github:
    repo: koffiyohanerickouakou/coovia
    branch: main
  dockerfile_path: backend/Dockerfile
  run_command: /usr/local/bin/start.sh
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  health_check:
    http_path: /api/health
  envs:
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "false"
  - key: CACHE_DRIVER
    value: file
  - key: SESSION_DRIVER
    value: file
  - key: QUEUE_CONNECTION
    value: sync
  - key: DB_CONNECTION
    value: pgsql
  - key: DB_HOST
    value: ${db.DATABASE_HOST}
  - key: DB_PORT
    value: ${db.DATABASE_PORT}
  - key: DB_DATABASE
    value: ${db.DATABASE_NAME}
  - key: DB_USERNAME
    value: ${db.DATABASE_USER}
  - key: DB_PASSWORD
    value: ${db.DATABASE_PASSWORD}
  - key: CLOUDFLARE_R2_ACCESS_KEY_ID
    value: d8bd4ac4100f9d1af000d8b59c0d5810
  - key: CLOUDFLARE_R2_SECRET_ACCESS_KEY
    value: 67482928c8d1093677ad71131d0d63dcbf886d4e7385f1b904e7958af159ac1c
  - key: CLOUDFLARE_R2_BUCKET
    value: coovia-files
  - key: CLOUDFLARE_R2_URL
    value: https://coovia-files.abf701097f61a1d3954f38fcc6b41e83.r2.cloudflarestorage.com
  - key: CLOUDFLARE_R2_ENDPOINT
    value: https://abf701097f61a1d3954f38fcc6b41e83.r2.cloudflarestorage.com
  - key: FILESYSTEM_DISK
    value: r2

databases:
- name: db
  engine: PG
  version: "15"
