import type { PaymentGateway } from "../types/payment"

export const flutterwaveGateway: PaymentGateway = {
  id: "flutterwave",
  name: "Flutterwave",
  type: "flutterwave",
  country: "Multi-pays Afrique",
  countryCode: "MULTI",
  logo: "/placeholder.svg?height=40&width=40&text=Flutterwave",
  isActive: true,
  supportedMethods: [
    {
      id: "mtn-momo-gh-flutter",
      name: "MTN Mobile Money Ghana",
      type: "mobile-money",
      country: "Ghana",
      countryCode: "GH",
      provider: "MTN",
      details: "+233 XX XXX XXXX",
      logo: "/placeholder.svg?height=24&width=24&text=MTN",
      isActive: true,
    },
    {
      id: "vodafone-cash-gh",
      name: "Vodafone Cash Ghana",
      type: "mobile-money",
      country: "Ghana",
      countryCode: "GH",
      provider: "Vodafone",
      details: "+233 XX XXX XXXX",
      logo: "/placeholder.svg?height=24&width=24&text=VF",
      isActive: true,
    },
    {
      id: "bank-transfer-gh",
      name: "Virement Bancaire Ghana",
      type: "bank-transfer",
      country: "Ghana",
      countryCode: "GH",
      provider: "GCB Bank, Ecobank",
      details: "Compte bancaire local",
      logo: "/placeholder.svg?height=24&width=24&text=BANK",
      isActive: true,
    },
    {
      id: "visa-flutter",
      name: "Visa Card",
      type: "card",
      country: "International",
      countryCode: "INTL",
      provider: "Visa",
      details: "**** **** **** XXXX",
      logo: "/placeholder.svg?height=24&width=24&text=VISA",
      isActive: true,
    },
  ],
}
