import type { PaymentGateway } from "../types/payment"

export const pawapayGateway: PaymentGateway = {
  id: "pawapay",
  name: "PawaPay",
  type: "pawapay",
  country: "Multi-pays Afrique de l'Est",
  countryCode: "MULTI",
  logo: "/placeholder.svg?height=40&width=40&text=PawaPay",
  isActive: true,
  supportedMethods: [
    {
      id: "mtn-money-ug",
      name: "MTN Mobile Money Ouganda",
      type: "mobile-money",
      country: "Ouganda",
      countryCode: "UG",
      provider: "MTN",
      details: "+256 77 XXX XXXX",
      logo: "/placeholder.svg?height=24&width=24&text=MTN",
      isActive: true,
    },
    {
      id: "airtel-money-ug",
      name: "Airtel Money Ouganda",
      type: "mobile-money",
      country: "Ouganda",
      countryCode: "UG",
      provider: "Airtel",
      details: "+256 70 XXX XXXX",
      logo: "/placeholder.svg?height=24&width=24&text=AIRTEL",
      isActive: true,
    },
    {
      id: "mpesa-ke",
      name: "M-Pesa Kenya",
      type: "mobile-money",
      country: "Kenya",
      countryCode: "KE",
      provider: "Safaricom",
      details: "+254 7XX XXX XXX",
      logo: "/placeholder.svg?height=24&width=24&text=MPESA",
      isActive: true,
    },
    {
      id: "tigopesa-tz",
      name: "Tigo Pesa Tanzanie",
      type: "mobile-money",
      country: "Tanzanie",
      countryCode: "TZ",
      provider: "Tigo",
      details: "+255 7XX XXX XXX",
      logo: "/placeholder.svg?height=24&width=24&text=TIGO",
      isActive: true,
    },
  ],
}
