import type { PaymentGateway } from "../types/payment"

export const paydunyaGateway: PaymentGateway = {
  id: "paydunya",
  name: "PayDunya",
  type: "paydunya",
  country: "Multi-pays Afrique de l'Ouest",
  countryCode: "MULTI",
  logo: "src/assets/images/gateways/paydunya.png",
  isActive: true,
  supportedMethods: [
    {
      id: "orange-money-ci",
      name: "Orange Money",
      type: "mobile-money",
      country: "Côte d'Ivoire",
      countryCode: "CI",
      provider: "Orange",
      details: "+225 XX XX XX XX XX",
      logo: "src/assets/images/orange-money.jpg",
      isActive: true,
    },
    {
      id: "orange-money-sn",
      name: "Orange Money",
      type: "mobile-money",
      country: "Sénégal",
      countryCode: "SN",
      provider: "Orange",
      details: "+221 XX XXX XX XX",
      logo: "src/assets/images/orange-money.jpg",
      isActive: true,
    },
    {
      id: "moov-money-ci",
      name: "Moov Money",
      type: "mobile-money",
      country: "Côte d'Ivoire",
      countryCode: "CI",
      provider: "Moov",
      details: "+225 XX XX XX XX XX",
      logo: "/images/moov-money.png",
      isActive: true,
    },
    {
      id: "mtn-money-ci",
      name: "MTN Mobile Money",
      type: "mobile-money",
      country: "Côte d'Ivoire",
      countryCode: "CI",
      provider: "MTN",
      details: "+225 XX XX XX XX XX",
      logo: "/images/mtn-money.png",
      isActive: true,
    },
    {
      id: "wave-ci",
      name: "Wave",
      type: "mobile-money",
      country: "Côte d'Ivoire",
      countryCode: "CI",
      provider: "Wave",
      details: "+225 XX XX XX XX XX",
      logo: "/images/wave-money.png",
      isActive: true,
    },
  ],
}
