{
  "name": "coovia-api",
  "type": "web",
  "build_command": "composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache",
  "run_command": "php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=$PORT",
  "environment": "php",
  "envs": {
    "APP_ENV": "production",
    "APP_DEBUG": "false",
    "CACHE_DRIVER": "file",
    "SESSION_DRIVER": "file",
    "QUEUE_CONNECTION": "sync"
  }
}
