import type { PaymentGateway } from "../types/payment"

export const paystackGateway: PaymentGateway = {
  id: "paystack",
  name: "Paystack",
  type: "paystack",
  country: "Nigeria",
  countryCode: "NG",
  logo: "/placeholder.svg?height=40&width=40&text=Paystack",
  isActive: true,
  supportedMethods: [
    {
      id: "visa-paystack",
      name: "Visa Card",
      type: "card",
      country: "International",
      countryCode: "INTL",
      provider: "Visa",
      details: "**** **** **** XXXX",
      logo: "/placeholder.svg?height=24&width=24&text=VISA",
      isActive: true,
    },
    {
      id: "mastercard-paystack",
      name: "MasterCard",
      type: "card",
      country: "International",
      countryCode: "INTL",
      provider: "MasterCard",
      details: "**** **** **** XXXX",
      logo: "/placeholder.svg?height=24&width=24&text=MC",
      isActive: true,
    },
    {
      id: "bank-transfer-ng",
      name: "Virement Bancaire Nigeria",
      type: "bank-transfer",
      country: "Nigeria",
      countryCode: "NG",
      provider: "Banques nigérianes",
      details: "Compte bancaire local",
      logo: "/placeholder.svg?height=24&width=24&text=BANK",
      isActive: true,
    },
    {
      id: "ussd-ng",
      name: "USSD Nigeria",
      type: "mobile-money",
      country: "Nigeria",
      countryCode: "NG",
      provider: "Opérateurs locaux",
      details: "*XXX#",
      logo: "/placeholder.svg?height=24&width=24&text=USSD",
      isActive: true,
    },
  ],
}
