/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreSelectionRouteImport } from './routes/store-selection'
import { Route as CreateStoreRouteImport } from './routes/create-store'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as BoutiqueStoreIdRouteImport } from './routes/boutique/$storeId'
import { Route as AuthenticatedStoreIdRouteImport } from './routes/_authenticated/$storeId'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedStoresIndexRouteImport } from './routes/_authenticated/stores/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedProduitsIndexRouteImport } from './routes/_authenticated/produits/index'
import { Route as AuthenticatedMarketingIndexRouteImport } from './routes/_authenticated/marketing/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedStoreIdTasksRouteImport } from './routes/_authenticated/$storeId.tasks'
import { Route as AuthenticatedStoreIdSettingsRouteImport } from './routes/_authenticated/$storeId.settings'
import { Route as AuthenticatedStoreIdProduitsRouteImport } from './routes/_authenticated/$storeId/produits'
import { Route as AuthenticatedStoreIdDashboardRouteImport } from './routes/_authenticated/$storeId.dashboard'
import { Route as AuthenticatedStoreIdCommandesRouteImport } from './routes/_authenticated/$storeId/commandes'
import { Route as AuthenticatedStoreIdClientsRouteImport } from './routes/_authenticated/$storeId.clients'
import { Route as AuthenticatedStoreIdAppsRouteImport } from './routes/_authenticated/$storeId.apps'
import { Route as AuthenticatedMarketingAjouterIndexRouteImport } from './routes/_authenticated/marketing/ajouter/index'
import { Route as AuthenticatedStoreIdProduitsIndexRouteImport } from './routes/_authenticated/$storeId/produits/index'
import { Route as AuthenticatedStoreIdMediaIndexRouteImport } from './routes/_authenticated/$storeId/media/index'
import { Route as AuthenticatedStoreIdCommandesIndexRouteImport } from './routes/_authenticated/$storeId/commandes/index'
import { Route as AuthenticatedStoreIdProduitsAddproduitRouteImport } from './routes/_authenticated/$storeId/produits/addproduit'
import { Route as AuthenticatedStoreIdMediaUploadRouteImport } from './routes/_authenticated/$storeId/media/upload'
import { Route as AuthenticatedStoreIdCommandesNouvelleRouteImport } from './routes/_authenticated/$storeId/commandes/nouvelle'

const StoreSelectionRoute = StoreSelectionRouteImport.update({
  id: '/store-selection',
  path: '/store-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateStoreRoute = CreateStoreRouteImport.update({
  id: '/create-store',
  path: '/create-store',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BoutiqueStoreIdRoute = BoutiqueStoreIdRouteImport.update({
  id: '/boutique/$storeId',
  path: '/boutique/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoreIdRoute = AuthenticatedStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoresIndexRoute =
  AuthenticatedStoresIndexRouteImport.update({
    id: '/stores/',
    path: '/stores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedProduitsIndexRoute =
  AuthenticatedProduitsIndexRouteImport.update({
    id: '/produits/',
    path: '/produits/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingIndexRoute =
  AuthenticatedMarketingIndexRouteImport.update({
    id: '/marketing/',
    path: '/marketing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedStoreIdTasksRoute =
  AuthenticatedStoreIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdSettingsRoute =
  AuthenticatedStoreIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdProduitsRoute =
  AuthenticatedStoreIdProduitsRouteImport.update({
    id: '/produits',
    path: '/produits',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdDashboardRoute =
  AuthenticatedStoreIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdCommandesRoute =
  AuthenticatedStoreIdCommandesRouteImport.update({
    id: '/commandes',
    path: '/commandes',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdClientsRoute =
  AuthenticatedStoreIdClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdAppsRoute =
  AuthenticatedStoreIdAppsRouteImport.update({
    id: '/apps',
    path: '/apps',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedMarketingAjouterIndexRoute =
  AuthenticatedMarketingAjouterIndexRouteImport.update({
    id: '/marketing/ajouter/',
    path: '/marketing/ajouter/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoreIdProduitsIndexRoute =
  AuthenticatedStoreIdProduitsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStoreIdProduitsRoute,
  } as any)
const AuthenticatedStoreIdMediaIndexRoute =
  AuthenticatedStoreIdMediaIndexRouteImport.update({
    id: '/media/',
    path: '/media/',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdCommandesIndexRoute =
  AuthenticatedStoreIdCommandesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStoreIdCommandesRoute,
  } as any)
const AuthenticatedStoreIdProduitsAddproduitRoute =
  AuthenticatedStoreIdProduitsAddproduitRouteImport.update({
    id: '/addproduit',
    path: '/addproduit',
    getParentRoute: () => AuthenticatedStoreIdProduitsRoute,
  } as any)
const AuthenticatedStoreIdMediaUploadRoute =
  AuthenticatedStoreIdMediaUploadRouteImport.update({
    id: '/media/upload',
    path: '/media/upload',
    getParentRoute: () => AuthenticatedStoreIdRoute,
  } as any)
const AuthenticatedStoreIdCommandesNouvelleRoute =
  AuthenticatedStoreIdCommandesNouvelleRouteImport.update({
    id: '/nouvelle',
    path: '/nouvelle',
    getParentRoute: () => AuthenticatedStoreIdCommandesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/create-store': typeof CreateStoreRoute
  '/store-selection': typeof StoreSelectionRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/$storeId': typeof AuthenticatedStoreIdRouteWithChildren
  '/boutique/$storeId': typeof BoutiqueStoreIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/$storeId/apps': typeof AuthenticatedStoreIdAppsRoute
  '/$storeId/clients': typeof AuthenticatedStoreIdClientsRoute
  '/$storeId/commandes': typeof AuthenticatedStoreIdCommandesRouteWithChildren
  '/$storeId/dashboard': typeof AuthenticatedStoreIdDashboardRoute
  '/$storeId/produits': typeof AuthenticatedStoreIdProduitsRouteWithChildren
  '/$storeId/settings': typeof AuthenticatedStoreIdSettingsRoute
  '/$storeId/tasks': typeof AuthenticatedStoreIdTasksRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/marketing': typeof AuthenticatedMarketingIndexRoute
  '/produits': typeof AuthenticatedProduitsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/stores': typeof AuthenticatedStoresIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/$storeId/commandes/nouvelle': typeof AuthenticatedStoreIdCommandesNouvelleRoute
  '/$storeId/media/upload': typeof AuthenticatedStoreIdMediaUploadRoute
  '/$storeId/produits/addproduit': typeof AuthenticatedStoreIdProduitsAddproduitRoute
  '/$storeId/commandes/': typeof AuthenticatedStoreIdCommandesIndexRoute
  '/$storeId/media': typeof AuthenticatedStoreIdMediaIndexRoute
  '/$storeId/produits/': typeof AuthenticatedStoreIdProduitsIndexRoute
  '/marketing/ajouter': typeof AuthenticatedMarketingAjouterIndexRoute
}
export interface FileRoutesByTo {
  '/create-store': typeof CreateStoreRoute
  '/store-selection': typeof StoreSelectionRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/$storeId': typeof AuthenticatedStoreIdRouteWithChildren
  '/boutique/$storeId': typeof BoutiqueStoreIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/$storeId/apps': typeof AuthenticatedStoreIdAppsRoute
  '/$storeId/clients': typeof AuthenticatedStoreIdClientsRoute
  '/$storeId/dashboard': typeof AuthenticatedStoreIdDashboardRoute
  '/$storeId/settings': typeof AuthenticatedStoreIdSettingsRoute
  '/$storeId/tasks': typeof AuthenticatedStoreIdTasksRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/marketing': typeof AuthenticatedMarketingIndexRoute
  '/produits': typeof AuthenticatedProduitsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/stores': typeof AuthenticatedStoresIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/$storeId/commandes/nouvelle': typeof AuthenticatedStoreIdCommandesNouvelleRoute
  '/$storeId/media/upload': typeof AuthenticatedStoreIdMediaUploadRoute
  '/$storeId/produits/addproduit': typeof AuthenticatedStoreIdProduitsAddproduitRoute
  '/$storeId/commandes': typeof AuthenticatedStoreIdCommandesIndexRoute
  '/$storeId/media': typeof AuthenticatedStoreIdMediaIndexRoute
  '/$storeId/produits': typeof AuthenticatedStoreIdProduitsIndexRoute
  '/marketing/ajouter': typeof AuthenticatedMarketingAjouterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/create-store': typeof CreateStoreRoute
  '/store-selection': typeof StoreSelectionRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/$storeId': typeof AuthenticatedStoreIdRouteWithChildren
  '/boutique/$storeId': typeof BoutiqueStoreIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$storeId/apps': typeof AuthenticatedStoreIdAppsRoute
  '/_authenticated/$storeId/clients': typeof AuthenticatedStoreIdClientsRoute
  '/_authenticated/$storeId/commandes': typeof AuthenticatedStoreIdCommandesRouteWithChildren
  '/_authenticated/$storeId/dashboard': typeof AuthenticatedStoreIdDashboardRoute
  '/_authenticated/$storeId/produits': typeof AuthenticatedStoreIdProduitsRouteWithChildren
  '/_authenticated/$storeId/settings': typeof AuthenticatedStoreIdSettingsRoute
  '/_authenticated/$storeId/tasks': typeof AuthenticatedStoreIdTasksRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/_authenticated/produits/': typeof AuthenticatedProduitsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/stores/': typeof AuthenticatedStoresIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/$storeId/commandes/nouvelle': typeof AuthenticatedStoreIdCommandesNouvelleRoute
  '/_authenticated/$storeId/media/upload': typeof AuthenticatedStoreIdMediaUploadRoute
  '/_authenticated/$storeId/produits/addproduit': typeof AuthenticatedStoreIdProduitsAddproduitRoute
  '/_authenticated/$storeId/commandes/': typeof AuthenticatedStoreIdCommandesIndexRoute
  '/_authenticated/$storeId/media/': typeof AuthenticatedStoreIdMediaIndexRoute
  '/_authenticated/$storeId/produits/': typeof AuthenticatedStoreIdProduitsIndexRoute
  '/_authenticated/marketing/ajouter/': typeof AuthenticatedMarketingAjouterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/create-store'
    | '/store-selection'
    | '/settings'
    | '/clerk/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/$storeId'
    | '/boutique/$storeId'
    | '/'
    | '/$storeId/apps'
    | '/$storeId/clients'
    | '/$storeId/commandes'
    | '/$storeId/dashboard'
    | '/$storeId/produits'
    | '/$storeId/settings'
    | '/$storeId/tasks'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/clients'
    | '/help-center'
    | '/marketing'
    | '/produits'
    | '/settings/'
    | '/stores'
    | '/tasks'
    | '/users'
    | '/$storeId/commandes/nouvelle'
    | '/$storeId/media/upload'
    | '/$storeId/produits/addproduit'
    | '/$storeId/commandes/'
    | '/$storeId/media'
    | '/$storeId/produits/'
    | '/marketing/ajouter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create-store'
    | '/store-selection'
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/$storeId'
    | '/boutique/$storeId'
    | '/'
    | '/$storeId/apps'
    | '/$storeId/clients'
    | '/$storeId/dashboard'
    | '/$storeId/settings'
    | '/$storeId/tasks'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/clients'
    | '/help-center'
    | '/marketing'
    | '/produits'
    | '/settings'
    | '/stores'
    | '/tasks'
    | '/users'
    | '/$storeId/commandes/nouvelle'
    | '/$storeId/media/upload'
    | '/$storeId/produits/addproduit'
    | '/$storeId/commandes'
    | '/$storeId/media'
    | '/$storeId/produits'
    | '/marketing/ajouter'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/create-store'
    | '/store-selection'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/$storeId'
    | '/boutique/$storeId'
    | '/_authenticated/'
    | '/_authenticated/$storeId/apps'
    | '/_authenticated/$storeId/clients'
    | '/_authenticated/$storeId/commandes'
    | '/_authenticated/$storeId/dashboard'
    | '/_authenticated/$storeId/produits'
    | '/_authenticated/$storeId/settings'
    | '/_authenticated/$storeId/tasks'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/clients/'
    | '/_authenticated/help-center/'
    | '/_authenticated/marketing/'
    | '/_authenticated/produits/'
    | '/_authenticated/settings/'
    | '/_authenticated/stores/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/$storeId/commandes/nouvelle'
    | '/_authenticated/$storeId/media/upload'
    | '/_authenticated/$storeId/produits/addproduit'
    | '/_authenticated/$storeId/commandes/'
    | '/_authenticated/$storeId/media/'
    | '/_authenticated/$storeId/produits/'
    | '/_authenticated/marketing/ajouter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  CreateStoreRoute: typeof CreateStoreRoute
  StoreSelectionRoute: typeof StoreSelectionRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  BoutiqueStoreIdRoute: typeof BoutiqueStoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store-selection': {
      id: '/store-selection'
      path: '/store-selection'
      fullPath: '/store-selection'
      preLoaderRoute: typeof StoreSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-store': {
      id: '/create-store'
      path: '/create-store'
      fullPath: '/create-store'
      preLoaderRoute: typeof CreateStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/boutique/$storeId': {
      id: '/boutique/$storeId'
      path: '/boutique/$storeId'
      fullPath: '/boutique/$storeId'
      preLoaderRoute: typeof BoutiqueStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$storeId': {
      id: '/_authenticated/$storeId'
      path: '/$storeId'
      fullPath: '/$storeId'
      preLoaderRoute: typeof AuthenticatedStoreIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: '/'
      fullPath: '/clerk/'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/': {
      id: '/_authenticated/stores/'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AuthenticatedStoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/produits/': {
      id: '/_authenticated/produits/'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof AuthenticatedProduitsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing/': {
      id: '/_authenticated/marketing/'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/$storeId/tasks': {
      id: '/_authenticated/$storeId/tasks'
      path: '/tasks'
      fullPath: '/$storeId/tasks'
      preLoaderRoute: typeof AuthenticatedStoreIdTasksRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/settings': {
      id: '/_authenticated/$storeId/settings'
      path: '/settings'
      fullPath: '/$storeId/settings'
      preLoaderRoute: typeof AuthenticatedStoreIdSettingsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/produits': {
      id: '/_authenticated/$storeId/produits'
      path: '/produits'
      fullPath: '/$storeId/produits'
      preLoaderRoute: typeof AuthenticatedStoreIdProduitsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/dashboard': {
      id: '/_authenticated/$storeId/dashboard'
      path: '/dashboard'
      fullPath: '/$storeId/dashboard'
      preLoaderRoute: typeof AuthenticatedStoreIdDashboardRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/commandes': {
      id: '/_authenticated/$storeId/commandes'
      path: '/commandes'
      fullPath: '/$storeId/commandes'
      preLoaderRoute: typeof AuthenticatedStoreIdCommandesRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/clients': {
      id: '/_authenticated/$storeId/clients'
      path: '/clients'
      fullPath: '/$storeId/clients'
      preLoaderRoute: typeof AuthenticatedStoreIdClientsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/apps': {
      id: '/_authenticated/$storeId/apps'
      path: '/apps'
      fullPath: '/$storeId/apps'
      preLoaderRoute: typeof AuthenticatedStoreIdAppsRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/marketing/ajouter/': {
      id: '/_authenticated/marketing/ajouter/'
      path: '/marketing/ajouter'
      fullPath: '/marketing/ajouter'
      preLoaderRoute: typeof AuthenticatedMarketingAjouterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$storeId/produits/': {
      id: '/_authenticated/$storeId/produits/'
      path: '/'
      fullPath: '/$storeId/produits/'
      preLoaderRoute: typeof AuthenticatedStoreIdProduitsIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdProduitsRoute
    }
    '/_authenticated/$storeId/media/': {
      id: '/_authenticated/$storeId/media/'
      path: '/media'
      fullPath: '/$storeId/media'
      preLoaderRoute: typeof AuthenticatedStoreIdMediaIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/commandes/': {
      id: '/_authenticated/$storeId/commandes/'
      path: '/'
      fullPath: '/$storeId/commandes/'
      preLoaderRoute: typeof AuthenticatedStoreIdCommandesIndexRouteImport
      parentRoute: typeof AuthenticatedStoreIdCommandesRoute
    }
    '/_authenticated/$storeId/produits/addproduit': {
      id: '/_authenticated/$storeId/produits/addproduit'
      path: '/addproduit'
      fullPath: '/$storeId/produits/addproduit'
      preLoaderRoute: typeof AuthenticatedStoreIdProduitsAddproduitRouteImport
      parentRoute: typeof AuthenticatedStoreIdProduitsRoute
    }
    '/_authenticated/$storeId/media/upload': {
      id: '/_authenticated/$storeId/media/upload'
      path: '/media/upload'
      fullPath: '/$storeId/media/upload'
      preLoaderRoute: typeof AuthenticatedStoreIdMediaUploadRouteImport
      parentRoute: typeof AuthenticatedStoreIdRoute
    }
    '/_authenticated/$storeId/commandes/nouvelle': {
      id: '/_authenticated/$storeId/commandes/nouvelle'
      path: '/nouvelle'
      fullPath: '/$storeId/commandes/nouvelle'
      preLoaderRoute: typeof AuthenticatedStoreIdCommandesNouvelleRouteImport
      parentRoute: typeof AuthenticatedStoreIdCommandesRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedStoreIdCommandesRouteChildren {
  AuthenticatedStoreIdCommandesNouvelleRoute: typeof AuthenticatedStoreIdCommandesNouvelleRoute
  AuthenticatedStoreIdCommandesIndexRoute: typeof AuthenticatedStoreIdCommandesIndexRoute
}

const AuthenticatedStoreIdCommandesRouteChildren: AuthenticatedStoreIdCommandesRouteChildren =
  {
    AuthenticatedStoreIdCommandesNouvelleRoute:
      AuthenticatedStoreIdCommandesNouvelleRoute,
    AuthenticatedStoreIdCommandesIndexRoute:
      AuthenticatedStoreIdCommandesIndexRoute,
  }

const AuthenticatedStoreIdCommandesRouteWithChildren =
  AuthenticatedStoreIdCommandesRoute._addFileChildren(
    AuthenticatedStoreIdCommandesRouteChildren,
  )

interface AuthenticatedStoreIdProduitsRouteChildren {
  AuthenticatedStoreIdProduitsAddproduitRoute: typeof AuthenticatedStoreIdProduitsAddproduitRoute
  AuthenticatedStoreIdProduitsIndexRoute: typeof AuthenticatedStoreIdProduitsIndexRoute
}

const AuthenticatedStoreIdProduitsRouteChildren: AuthenticatedStoreIdProduitsRouteChildren =
  {
    AuthenticatedStoreIdProduitsAddproduitRoute:
      AuthenticatedStoreIdProduitsAddproduitRoute,
    AuthenticatedStoreIdProduitsIndexRoute:
      AuthenticatedStoreIdProduitsIndexRoute,
  }

const AuthenticatedStoreIdProduitsRouteWithChildren =
  AuthenticatedStoreIdProduitsRoute._addFileChildren(
    AuthenticatedStoreIdProduitsRouteChildren,
  )

interface AuthenticatedStoreIdRouteChildren {
  AuthenticatedStoreIdAppsRoute: typeof AuthenticatedStoreIdAppsRoute
  AuthenticatedStoreIdClientsRoute: typeof AuthenticatedStoreIdClientsRoute
  AuthenticatedStoreIdCommandesRoute: typeof AuthenticatedStoreIdCommandesRouteWithChildren
  AuthenticatedStoreIdDashboardRoute: typeof AuthenticatedStoreIdDashboardRoute
  AuthenticatedStoreIdProduitsRoute: typeof AuthenticatedStoreIdProduitsRouteWithChildren
  AuthenticatedStoreIdSettingsRoute: typeof AuthenticatedStoreIdSettingsRoute
  AuthenticatedStoreIdTasksRoute: typeof AuthenticatedStoreIdTasksRoute
  AuthenticatedStoreIdMediaUploadRoute: typeof AuthenticatedStoreIdMediaUploadRoute
  AuthenticatedStoreIdMediaIndexRoute: typeof AuthenticatedStoreIdMediaIndexRoute
}

const AuthenticatedStoreIdRouteChildren: AuthenticatedStoreIdRouteChildren = {
  AuthenticatedStoreIdAppsRoute: AuthenticatedStoreIdAppsRoute,
  AuthenticatedStoreIdClientsRoute: AuthenticatedStoreIdClientsRoute,
  AuthenticatedStoreIdCommandesRoute:
    AuthenticatedStoreIdCommandesRouteWithChildren,
  AuthenticatedStoreIdDashboardRoute: AuthenticatedStoreIdDashboardRoute,
  AuthenticatedStoreIdProduitsRoute:
    AuthenticatedStoreIdProduitsRouteWithChildren,
  AuthenticatedStoreIdSettingsRoute: AuthenticatedStoreIdSettingsRoute,
  AuthenticatedStoreIdTasksRoute: AuthenticatedStoreIdTasksRoute,
  AuthenticatedStoreIdMediaUploadRoute: AuthenticatedStoreIdMediaUploadRoute,
  AuthenticatedStoreIdMediaIndexRoute: AuthenticatedStoreIdMediaIndexRoute,
}

const AuthenticatedStoreIdRouteWithChildren =
  AuthenticatedStoreIdRoute._addFileChildren(AuthenticatedStoreIdRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedStoreIdRoute: typeof AuthenticatedStoreIdRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedMarketingIndexRoute: typeof AuthenticatedMarketingIndexRoute
  AuthenticatedProduitsIndexRoute: typeof AuthenticatedProduitsIndexRoute
  AuthenticatedStoresIndexRoute: typeof AuthenticatedStoresIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedMarketingAjouterIndexRoute: typeof AuthenticatedMarketingAjouterIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedStoreIdRoute: AuthenticatedStoreIdRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedMarketingIndexRoute: AuthenticatedMarketingIndexRoute,
  AuthenticatedProduitsIndexRoute: AuthenticatedProduitsIndexRoute,
  AuthenticatedStoresIndexRoute: AuthenticatedStoresIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedMarketingAjouterIndexRoute:
    AuthenticatedMarketingAjouterIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  CreateStoreRoute: CreateStoreRoute,
  StoreSelectionRoute: StoreSelectionRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  BoutiqueStoreIdRoute: BoutiqueStoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
