import type { PaymentGateway } from "../types/payment"

export const fedapayGateway: PaymentGateway = {
  id: "fedapay",
  name: "FedaPay",
  type: "fedapay",
  country: "Bénin",
  countryCode: "BJ",
  logo: "/placeholder.svg?height=40&width=40&text=FedaPay",
  isActive: true,
  supportedMethods: [
    {
      id: "mtn-money-bj",
      name: "MTN Mobile Money Bénin",
      type: "mobile-money",
      country: "Bénin",
      countryCode: "BJ",
      provider: "MTN",
      details: "+229 XX XX XX XX",
      logo: "/placeholder.svg?height=24&width=24&text=MTN",
      isActive: true,
    },
    {
      id: "moov-money-bj-feda",
      name: "Moov Money Bénin",
      type: "mobile-money",
      country: "Bénin",
      countryCode: "BJ",
      provider: "Moov",
      details: "+229 XX XX XX XX",
      logo: "/placeholder.svg?height=24&width=24&text=MV",
      isActive: true,
    },
    {
      id: "mastercard-fedapay",
      name: "MasterCard",
      type: "card",
      country: "International",
      countryCode: "INTL",
      provider: "MasterCard",
      details: "**** **** **** XXXX",
      logo: "/placeholder.svg?height=24&width=24&text=MC",
      isActive: true,
    },
    {
      id: "bank-transfer-bj",
      name: "Virement Bancaire Bénin",
      type: "bank-transfer",
      country: "Bénin",
      countryCode: "BJ",
      provider: "Banques locales",
      details: "Compte bancaire local",
      logo: "/placeholder.svg?height=24&width=24&text=BANK",
      isActive: true,
    },
  ],
}
